# Generated by Django 3.1.7 on 2021-07-19 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.BigIntegerField(default=0, editable=False, verbose_name='Просмотры')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.blog', verbose_name='Пост')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='post_views',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.views', verbose_name='Просмотры'),
        ),
    ]
