# Generated by Django 3.1.7 on 2021-07-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Blog',
        ),
    ]
