# Generated by Django 3.1.7 on 2021-07-19 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='views',
            name='post',
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_views',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.views', verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='views',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
