# Generated by Django 3.1.7 on 2021-07-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210719_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='views',
            field=models.BigIntegerField(default=0, editable=False, verbose_name='Просмотры'),
        ),
    ]
