# Generated by Django 3.1.7 on 2021-07-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210719_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='views',
            field=models.BigIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
