# Generated by Django 3.1.7 on 2021-07-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210719_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='views',
            options={'ordering': ['-id'], 'verbose_name': 'Просмотры', 'verbose_name_plural': 'Просмотры'},
        ),
    ]
