# Generated by Django 3.1.7 on 2021-07-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210719_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_views',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.views', verbose_name='Просмотры'),
        ),
    ]
